version: '3.8'

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile

    command: python /backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    entrypoint: 
      - /backend/wsgi_entrypoint.sh
    expose:
      - 8000
    depends_on: 
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data/
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on: 
      - backend
  
volumes: 
  postgres_data:

